[project]
name = 'Pan-Consciousness-Collective-Governance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.thought-quantization]
path = 'contracts/thought-quantization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
